apps/cart/urls.py
from django.conf.urls import url
from django.urls import re_path, path

from .views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    re_path(r'^add$', CartAddView.as_view(), name="add"),  # 购物车记录添加
    path('', CartInfoView.as_view(), name='show'),  # 购物车页面显示
    path('update', CartUpdateView.as_view(), name='update'),  # 购物车页面更新
    path('delete', CartDeleteView.as_view(), name="delete"),  # 购物车记录删除

]

apps/goods/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from apps.goods.views import *

urlpatterns = [
    path('index', IndexView.as_view(), name='index'),
    re_path(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),

]

apps/order/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from .views import OrderPlaceView, CommentView, OrderCommitView, OrderPayView, CheckPayView

urlpatterns = [
    path('place', OrderPlaceView.as_view(), name='place'),# 订单页面显示
    path('commit', OrderCommitView.as_view(), name='commit'),  # 订单创建
    re_path(r'^comment/(?P<order_id>.+)$', CommentView.as_view(), name='comment'),  # 订单评论
    path('pay', OrderPayView.as_view(), name='pay'), # 订单支付
    path('check', CheckPayView.as_view(), name='check'), # 查询订单支付结果

]

apps/user/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from apps.user.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', Login.as_view(), name='login'),
    re_path(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    path('info', UserInfoView.as_view(), name='userinfo'),
    re_path('^order/(?P<page>\d+)$', UserOrderView.as_view(), name='userorder'),
    path('site', UserSiteView.as_view(), name='usersite'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('address', AddressView.as_view(), name='address')

]

freshmarket/urls.py
from django.urls import include, re_path,path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^tinymce/', include('tinymce.urls')), # 富文本编辑器
    re_path(r'^search', include('haystack.urls')), # 全文检索框架
    re_path(r'^user/', include(('user.urls', 'user'), namespace='user')), # 用户模块
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')), # 购物车模块
    re_path(r'^order/', include(('order.urls', 'order'), namespace='order')), # 订单模块
    re_path(r'^', include(('goods.urls', 'goods'), namespace='goods')), # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django_redis import get_redis_connection

# Create your views here.
from django.views import View
from apps.goods.models import GoodsSKU


# /cart/add
class CartAddView(View):
    '''购物车记录增加'''

    def post(self, request):
        '''购物车记录添加'''

        user = request.user

        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据效验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 如果商品在redis中存在则累加购物车中商品的数目
            count += int(count)
        # 校验商品的库存是否足够
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 设置hash中sku_id对应的值
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车的条目数据
        total_count = conn.hlen(cart_key)

        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# /cart
class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面展示'''

    def get(self, request):
        # 获取登录用户
        user = request.user
        # 获取购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的总价格
            amount = sku.price * int(count)
            # 动态添加amount属性，保存商品的小计
            sku.amount = amount
            # 动态添加count属性，保存购物车中对应商品的数量
            sku.count = int(count)
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_price += int(amount)
            total_count += int(count)

        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus
        }
        for sku in skus:
            print(sku.count)
        return render(request, 'cart.html', context)


# /cart/update
class CartUpdateView(View):
    '''购物车记录更新'''

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据效验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存是否足够
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功 '})


# /cart/delete
class CartDeleteView(View):
    '''删除购物车记录'''

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除记录
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res':3, 'total_count':total_count, 'message':'删除成功'})

templates/base.html
{# 首页 详情页 列表页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}商品浏览首页{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block files %}
        <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
        <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="/static/js/slide.js"></script>
	{% endblock files %}
</head>
<body>

{# 网页顶部欢迎信息块 #}
{% block header_info %}
	<div class="header_con">
		<div class="header">
            <div class="user_link fl" style="margin-top: 5px;">
					<span>|</span>
					<a href="{% url 'user:userinfo' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:userorder' 1 %}">我的订单</a>
            </div>
			<div class="fr" style="margin-top: 5px;">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em style="color: #10fe00">{{ user.username }}</em>
                        <span>|</span>
					    <a href="{% url 'user:logout' %}">退出登录</a>
                    </div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">亲，请登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">免费注册</a>
				</div>
                {% endif %}

			</div>
		</div>		
	</div>
{% endblock header_info %}

 {# 网页顶部搜索框 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="fl"><img style="margin:-3px 0 0 -39px;" src="/static/images/logo2.png"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容 #}
{% block body %}{% endblock body %}

    <footer style="width: 100%;border-top:2px solid #42ad46;margin:30px 0;">
        <p style="text-align: center;margin-top: 10px">基于Django3.1弗锐氏生鲜电商网站</p>
        <p style="text-align: center;margin-top: 5px">设计学生：周圣恩</p>
    </footer>


{# 网页底部展示模块 #}
{% block bottom %}{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情 列表页 #}
{% extends 'base.html' %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>

    {# 详情页，列表页主题内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心3页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}弗锐氏-用户中心页面{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:userinfo' %}" {% if page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:userorder' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:usersite' %}" {% if page == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}弗锐氏浏览首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}弗锐氏-商品列表页面{% endblock %}

{% block main_content %}

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ type.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}" alt=""></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active" {% endif %}>默认</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active" {% endif %}>价格</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active" {% endif %} >人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in skus_page %}

                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                            <a href="{% url 'goods:detail' sku.id %}" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}


            </ul>

            <div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for page in pages %}
                    {% if page == skus_page.number %}
                        <a href="{% url 'goods:list' type.id page %}" class="active">{{ page }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}弗锐氏生鲜超市-登录页面{% endblock title %}
{% block header_info %}{% endblock header_info %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<img class="login_logo" src="{% static 'images/logo2.png' %}">
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="slogan fl">种的用心 · 吃的放心</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">没有帐户?立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}

						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<span class="pwd_error">{{ errmsg }}</span>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label style="color: #f0f9e8">记住用户名</label>
						</div>
                        <span class="pwd_error2">{{ errmsg2 }}</span>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>

	</div>

{% endblock body %}
	

templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}弗锐氏-提交订单页面{% endblock %}
{% block page_title %}提交订单{% endblock %}
{% block body %}

    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            {% for addr in addrs %}
                <dd><input type="radio" name="addr_id" value="{{ addr.id }}"
                           {% if addr.is_default %}checked{% endif %}>{{ addr.addr }} （{{ addr.receiver }}
                    收） {{ addr.phone }}</dd>
            {% endfor %}
        </dl>
        <a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" value="1">
            <label class="zhifubao"></label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for sku in skus %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ forloop.counter }}</li>
                <li class="col02"><img src="{{ sku.image.url }}" alt=""></li>
                <li class="col03">{{ sku.name }}</li>
                <li class="col04">{{ sku.unite }}</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">{{ sku.count }}</li>
                <li class="col07">{{ sku.amount }}元</li>
            </ul>
        {% endfor %}

    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
            <div class="total_pay">实付款：<b>{{ total_price }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        {% csrf_token %}
        <a href="javascript:;" sku_ids="{{ sku_ids }}" id="order_btn">提交订单</a>
    </div>
{% endblock body %}
{% block bottom %}
    <div class="popup_con">
        <div class="popup">
            <p>订单提交成功！</p>
        </div>

        <div class="mask"></div>
    </div>
{% endblock %}
{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $('#order_btn').click(function () {
            // 获取用户的选择的地址，支付方式， 要购买的商品的id的字符串

            let addr_id = $('input[name="addr_id"]:checked').val();
            let pay_method = $('input[name="pay_style"]:checked').val();
            let sku_ids = $(this).attr('sku_ids');
            let csrf = $('input[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url: "{% url 'order:commit' %}",
                type: 'post',
                data: {
                    addr_id: addr_id,
                    pay_method: pay_method,
                    sku_ids: sku_ids,
                    csrfmiddlewaretoken: csrf,
                },
                success: function (data) {
                    if (data.res === 5) {
                        localStorage.setItem('order_finish', 2);

                        $('.popup_con').fadeIn('fast', function () {
                            setTimeout(function () {
                                $('.popup_con').fadeOut('fast', function () {
                                    window.location.href = '/user/order/1';
                                });
                            }, 1000)
                        });
                    } else {
                        alert(data.errmsg)
                    }
                }

            })
        })


    </script>
{% endblock bottomfiles %}

templates/static_index.html
{% extends 'static_base.html' %}
{% load static %}
{% block title %}弗锐氏浏览首页(nginx生成的静态页面){% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
                            {% if address %}
							    <li><span>用户名：</span>{{ address.receiver }}</li>
							    <li><span>联系方式：</span>{{ address.phone }}</li>
							    <li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                                <li><span>用户名：</span>未设定默认用户</li>
							    <li><span>联系方式：</span>未设定默认联系方式</li>
							    <li><span>联系地址：</span>未设定默认地址</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for good in goods %}
                        <li>
                            <a href="{% url 'goods:detail' good.id %}"><img src="{{ good.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ good.price }}</span>
                                <span class="unit">{{ good.price }}/{{ good.unite }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                        {% empty %}
                            无历史浏览记录
                        {% endfor %}
			        </ul>
		</div>
		</div>
{% endblock right_content %}